version: '3'
services:
  #Mage
  mage:
    #image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: ./mage
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - ./mage/:/home/src/
    restart: on-failure:5

    # Postgres 
  postgresql:
    image: postgres:12.4
    ports:
      - 5432:5432
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
       PGDATA: /var/lib/postgresql/data 
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
      - ./postgres/sql_files/:/var/lib/postgres_sqlfiles
    command: psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /var/lib/postgres_sqlfiles/${SQL_FILE}




